[project]
name = "fraghub"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "altgraph",
    "annotated-doc",
    "annotated-types",
    "anyio",
    "bidict",
    "click",
    "fastapi",
    "fraghub-rust",
    "h11",
    "idna",
    "ijson",
    "llvmlite",
    "macholib",
    "numba",
    "numpy",
    "packaging",
    "pandas",
    "pandas-stubs",
    "pefile",
    "pillow",
    "psutil",
    "pydantic",
    "pydantic-core",
    "pyinstaller",
    "pyinstaller-hooks-contrib",
    "pyqt6",
    "pyqt6-qt6",
    "pyqt6-sip",
    "python-dateutil",
    "python-engineio",
    "python-socketio",
    "pytz",
    "pywin32-ctypes",
    "rdkit",
    "setuptools",
    "simple-websocket",
    "six",
    "starlette",
    "types-pytz",
    "typing-extensions",
    "typing-inspection",
    "tzdata",
    "uvicorn",
    "wsproto",
]

[tool.uv.workspace]
members = [
    "scripts/fraghub_rust",
]

[tool.uv.sources]
fraghub-rust = { workspace = true }
